sudo: required
language: node_js
install: curl https://install.meteor.com | /bin/sh
script:
  - VELOCITY_TEST_PACKAGES=1
  - meteor test-packages --driver-package=sanjo:jasmine ./
  - VELOCITY_CI=1
  - meteor test --driver-package sanjo:jasmine
